version: '3.8'
services:
  golf-club-api:
    build: .
    container_name: golf-club-api-aws
    ports:
      - "8080:8080"
    environment:

        SPRING_DATASOURCE_URL: jdbc:mysql://golf-club-db.cd06isyk8blt.us-east-2.rds.amazonaws.com:3306/golfclub?useSSL=false&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: <username>
        SPRING_DATASOURCE_PASSWORD: <Password>

